//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITWorkers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITWorkers()
        {
            this.Technologies = new HashSet<Technologies>();
        }
    
        public int IdWorker { get; set; }
        public string Name { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public int Experience { get; set; }
        public int LevelEnum { get; set; }
        public int RolEnum { get; set; }
        public Nullable<int> IdTask { get; set; }
        public Nullable<int> IdTeam { get; set; }
        public string Manager { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Technologies> Technologies { get; set; }
    }
}
