//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classrooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classrooms()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int IdClassroom { get; set; }
        public string Name { get; set; }
        public int Course { get; set; }
        public int Area { get; set; }
        public int IdSchool { get; set; }
    
        public virtual Schools Schools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students> Students { get; set; }
    }
}
