//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int IdStudent { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Nationality { get; set; }
        public int IdClassroom { get; set; }
    
        public virtual Classrooms Classrooms { get; set; }
    }
}
